project:
  type: website
  output-dir: docs

website:
  title: "LS 빅데이터스쿨 4기"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://ui-ju.github.io/uiju-blog/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



